version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: pip
    # Look for  files in the `root` directory
    directory: "/"
    #check daily
    schedule:
      interval: "weekly"
      # Check for  updates on Sundays
      day: "sunday"

